%% 
baseGroup = ['/gpfs/data/rudylab/William/171006_WT_EM1M3';...
'/gpfs/data/rudylab/William/171206_WT_EM1M3';...
'/gpfs/data/rudylab/William/171209_WT_EM1M3';...
'/gpfs/data/rudylab/William/180209_WT_EM1M3';...
'/gpfs/data/rudylab/William/180211_WT_EM1M3';...
'/gpfs/data/rudylab/William/180213_WT_EM1M3';...
'/gpfs/data/rudylab/William/180214_WT_EM1M3';...
'/gpfs/data/rudylab/William/180515_WT_EM1M3';...
'/gpfs/data/rudylab/William/180603_WT_EM1M3';...
'/gpfs/data/rudylab/William/180605_WT_EM1M3';...
'/gpfs/data/rudylab/William/180607_WT_EM1M3';...
'/gpfs/data/rudylab/William/180703_WT_EM1M3';...
'/gpfs/data/rudylab/William/180706_WT_EM1M3';...
'/gpfs/data/rudylab/William/180708_WT_EM1M3';...
'/gpfs/data/rudylab/William/180710_WT_EM1M3'];

basePath = pwd;
baseName = 'WT_EM1M3';
figfolder = fullfile(basePath,'SummaryFigures');
savefile = fullfile(basePath,[baseName,'.Optimization.PSS.lfp.mat']);

%% Rescale and collect data
% For PSS-Behavior analysis
groupPSS = [];
groupDepth = [];
for i = 1:size(baseGroup,1)
    
    cd(baseGroup(i,:));
    basename = bz_BasenameFromBasepath(baseGroup(i,:));

    sessionInfo = bz_getSessionInfo(baseGroup(i,:),'noPrompts',true);
    groupDepth = cat(3,groupDepth,rescaleCx(baseGroup(i,:),'BADOUT',true));

    load(fullfile(baseGroup(i,:),[basename,'.Optimization.PSS.lfp.mat']));
    groupPSS = bz_CollapseStruct([groupPSS PSpecSlope],3,'justcat',true); 
    
end

% Saving group structs
save(savefile,'groupPSS','groupDepth');

%% Mean/std for group...
%Pending proper error propagation and stats...



%% FIGURES


